"""add user personal fields

Revision ID: a9b79dc69fb6
Revises: e30ec1373011
Create Date: 2026-09-17 14:34:21.903383

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a9b79dc69fb6'
down_revision = 'e30ec1373011'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codice_fiscale', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('nome_cognome', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('data_nascita', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sesso', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('comune_stato_nascita', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['codice_fiscale'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('comune_stato_nascita')
        batch_op.drop_column('sesso')
        batch_op.drop_column('data_nascita')
        batch_op.drop_column('nome_cognome')
        batch_op.drop_column('codice_fiscale')

    with op.batch_alter_table('sos_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sos_contacts_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_sos_contacts_user_priority'), ['user_id', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_contacts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('monthly_aggregates', schema=None) as batch_op:
        batch_op.drop_constraint('uix_monthly_year_month', type_='unique')

    with op.batch_alter_table('hourly_daily_aggregates', schema=None) as batch_op:
        batch_op.drop_constraint('uix_hourly_daily_date_hour', type_='unique')

    op.create_table('playgrounds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('openingHours', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('indoor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fee', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('supervised', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gh5', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('playgrounds_pkey'))
    )
    with op.batch_alter_table('playgrounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playgrounds_gh5'), ['gh5'], unique=False)

    # ### end Alembic commands ###
