"""add_telemetry_tables

Revision ID: e30ec1373011
Revises: 20240907_add_sos_contacts
Create Date: 2026-09-10 15:28:58.861239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e30ec1373011'
down_revision = '20240907_add_sos_contacts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_aggregates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('avg_speed_kmh', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('daily_aggregates', schema=None) as batch_op:
        batch_op.create_index('idx_daily_aggregates_date', ['date'], unique=False)

    op.create_table('hourly_daily_aggregates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('hourly_avg_speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hourly_distance_km', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'hour'),
    sa.UniqueConstraint('date', 'hour', name='uix_hourly_daily_date_hour')
    )
    with op.batch_alter_table('hourly_daily_aggregates', schema=None) as batch_op:
        batch_op.create_index('idx_hourly_daily_aggregates_date', ['date'], unique=False)
        batch_op.create_index('idx_hourly_daily_aggregates_hour', ['hour'], unique=False)

    op.create_table('monthly_aggregates',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('daily_avg_speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('active_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('year', 'month'),
    sa.UniqueConstraint('year', 'month', name='uix_monthly_year_month')
    )
    with op.batch_alter_table('monthly_aggregates', schema=None) as batch_op:
        batch_op.create_index('idx_monthly_aggregates_month', ['month'], unique=False)
        batch_op.create_index('idx_monthly_aggregates_year', ['year'], unique=False)

    op.create_table('time_dim',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('week_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('time_dim', schema=None) as batch_op:
        batch_op.create_index('idx_time_dim_date', ['date'], unique=False)
        batch_op.create_index('idx_time_dim_year_month', ['year', 'month'], unique=False)

    op.create_table('yearly_aggregates',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('monthly_avg_speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    with op.batch_alter_table('yearly_aggregates', schema=None) as batch_op:
        batch_op.create_index('idx_yearly_aggregates_year', ['year'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('avg_speed_kmh', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active_time_sec', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('idx_activities_start_datetime', ['start_datetime'], unique=False)
        batch_op.create_index('idx_activities_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('idx_activities_user_id')
        batch_op.drop_index('idx_activities_start_datetime')

    op.drop_table('activities')
    with op.batch_alter_table('yearly_aggregates', schema=None) as batch_op:
        batch_op.drop_index('idx_yearly_aggregates_year')

    op.drop_table('yearly_aggregates')
    with op.batch_alter_table('time_dim', schema=None) as batch_op:
        batch_op.drop_index('idx_time_dim_year_month')
        batch_op.drop_index('idx_time_dim_date')

    op.drop_table('time_dim')
    with op.batch_alter_table('monthly_aggregates', schema=None) as batch_op:
        batch_op.drop_index('idx_monthly_aggregates_year')
        batch_op.drop_index('idx_monthly_aggregates_month')

    op.drop_table('monthly_aggregates')
    with op.batch_alter_table('hourly_daily_aggregates', schema=None) as batch_op:
        batch_op.drop_index('idx_hourly_daily_aggregates_hour')
        batch_op.drop_index('idx_hourly_daily_aggregates_date')

    op.drop_table('hourly_daily_aggregates')
    with op.batch_alter_table('daily_aggregates', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_aggregates_date')

    op.drop_table('daily_aggregates')
    # ### end Alembic commands ###
